name: Main branch

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  create_tag:
    if: github.event.pull_request.merged && github.event.pull_request.head.ref == 'production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // PR에 붙은 레이블 확인
            const labels = (await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            })).data.map(label => label.name);

            // PR에 붙은 레이블 중 버전 확인
            const version = labels.find(label => /^v(\d+\.\d+\.\d+)$/.test(label));
            if (version) {
              await github.rest.git.createTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: `${version}`,
                message: `${version}`,
                object: context.payload.pull_request.head.sha,
                type: 'commit',
                tagger: {
                  name: context.actor,
                  email: context.user.email || `${context.actor}@forspacelab.com`,
              });
            }