name: Production branch

on:
  pull_request:
    branches:
      - 'production'
    types:
      - closed

jobs:
  close_issue_and_create_pr_into_main:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Close issue and create PR into main from production
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = context.payload.pull_request.head.ref.split('/').pop();

            // release 이슈 확인
            const foundIssue = (await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['release', 'issue', version],
              state: 'open',
              sort: 'created',
              direction: 'desc',
              per_page: 1,
              page: 1,
            })).data[0];

            // release 이슈 종료
            if (foundIssue) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: foundIssue.number,
                state: 'closed',
              });
            }

            // production PR 생성
            const pr = (await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Release] Merge into main ${version}`,
              head: 'production',
              base: 'main',
            })).data;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['release', 'pr', version],
            });

            // release 이슈 assignees를 PR에 추가
            if (foundIssue) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                assignees: foundIssue.assignees.map(assignee => assignee.login),
              });
            }

