name: Release branch

on:
  push:
    branches:
      - 'release/*'
  pull_request:
    branches:
      - 'release/*'
    types:
      - closed

jobs:
  create_issue_for_release:
    if: github.event.created || github.event.forced
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = context.ref.split('/').pop();

            // 기존 이슈 확인
            const foundIssue = (await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['release', 'issue', version],
              state: 'open',
              sort: 'created',
              direction: 'desc',
              per_page: 1,
              page: 1
            })).data[0];

            // 기존 이슈 종료
            if (foundIssue) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: foundIssue.number,
                state: 'closed'
              });
            }

            // 기존 PR 확인
            const foundPr = (await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.ref,
              base: 'production',
              state: 'open',
              sort: 'created',
              direction: 'desc',
              per_page: 1,
              page: 1
            })).data[0];

            // 기존 PR 종료
            if (foundPr) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: foundPr.number,
                state: 'closed',
              });
            }

            // 이슈 생성
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Release] ${version}`,
              labels: ['release', 'issue', version],
            });
  add_comment_and_create_pr_into_production:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add comment and Create pr to merge into production from release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = context.ref.split('/').pop();

            // 이슈 불러오기
            const issue = (await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['release', 'issue', version],
              state: 'open',
              sort: 'created',
              direction: 'desc',
              per_page: 1,
              page: 1,
            })).data[0];

            // 이슈가 없으면 종료
            if (!issue) {
              return;
            }

            // 머지된 PR
            const mergedPr = (await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            })).data;
            // 머지된 PR의 커밋
            const commits = (await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            })).data;

            // into production PR
            let pr = (await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: context.ref,
              base: 'production',
              state: 'open',
              sort: 'created',
              direction: 'desc',
              per_page: 1,
              page: 1
            })).data[0];

            // into production PR 생성
            if (!pr) {
              pr = (await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `[Release] Merge into production ${new Date().toLocaleString('ko-KR', {timeZone: 'Asia/Seoul'})}`,
                head: context.ref,
                base: 'production',
                draft: true
              })).data;
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['release', 'pr', version]
              });
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `related to #${issue.number}`
              });
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `related to #${pr.number}`
              });
            }
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              assignees: ['${{ github.actor }}']
            });
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              assignees: ['${{ github.actor }}']
            });
            let comments = [];
            comments.push(`Merged PR: [${mergedPr.title}](${mergedPr.html_url}) #${mergedPr.number}`);
            comments.push(`- Branch: [${mergedPr.head.ref}](${mergedPr.head.repo.html_url}/tree/${mergedPr.head.ref})`);
            comments.push(`- Assingees: ${mergedPr.assignees.map(assignee => `@${assignee.login}`).join(', ')}`);
            comments.push('- Commit logs');
            comments = comments.concat(commits.map(commit => `> - [${commit.commit.message}](${commit.html_url})`));
            const mergedComment = comments.join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: mergedComment
            });
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: mergedComment
            });